export const allTutors = [
    { name: "Tomas Rios", course: "CIIC 3015", rating: 4.5 },
    { name: "Tony Soprano", course: "INGE4020", rating: 5 },
    { name: "Roberto Torres", course: "MATE3031", rating: 4.6 },
    { name: "Adrian Valdes", course: "CIPO3011", rating: 3 },
    { name: "Gerardo Castro", course: "INGL3133", rating: 2 },
    { name: "Jean Paul Vazquez", course: "CIIC 3015", rating: 4.5 },
    { name: "Dabel Ortiz", course: "INGE4020", rating: 5 },
    { name: "Joel Rodriguez", course: "MATE3031", rating: 4.6 },
    { name: "Jonathan Alicea", course: "CIPO3011", rating: 3 },
    { name: "Rey Ruiz", course: "INGL3133", rating: 0 },
    { name: "Marcos Rodriguez", course: "CIIC 3015", rating: 4.5 },
    { name: "Jose Collado", course: "INGE4020", rating: 5 },
    { name: "Alberto Ramon", course: "MATE3031", rating: 4.6 },
    { name: "Luis Forestier", course: "CIPO3011", rating: 3 },
    { name: "Miguel Alberto Monserrat", course: "INGL3133", rating: 2 },
    { name: "Carmen Rodriguez", course: "CIIC 3015", rating: 4.5 },
    { name: "Jaime Esteva", course: "INGE4020", rating: 5 },
    { name: "Laura Pacheco", course: "MATE3031", rating: 4.6 },
    { name: "Michael Perez", course: "CIPO3011", rating: 3 },
    { name: "Roberto 'Tito' Toro", course: "INGL3133", rating: 2 }
  ]; export default allTutors;